
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_MDM_0_DEVICE_ID,
		XPAR_MDM_0_BASEADDR,
		XPAR_MDM_0_BAUDRATE,
		XPAR_MDM_0_USE_PARITY,
		XPAR_MDM_0_ODD_PARITY,
		XPAR_MDM_0_DATA_BITS
	},
	{
		XPAR_RS232_DCE_DEVICE_ID,
		XPAR_RS232_DCE_BASEADDR,
		XPAR_RS232_DCE_BAUDRATE,
		XPAR_RS232_DCE_USE_PARITY,
		XPAR_RS232_DCE_ODD_PARITY,
		XPAR_RS232_DCE_DATA_BITS
	}
};


